//TODO: needed?
// public static Dictionary<string, string> Summoners = new Dictionary<string, string>()
//     {
//         { "224", Element.Dragon },
//         { "27", Element.Earth },
//         { "16", Element.Water },
//         { "156", Element.Life },
//         { "189", Element.Earth },
//         { "167", Element.Fire },
//         { "145", Element.Death },
//         { "5", Element.Fire },
//         { "71", Element.Water },
//         { "114", Element.Dragon },
//         { "178", Element.Water },
//         { "110", Element.Fire },
//         { "49", Element.Death },
//         { "88", Element.Dragon },
//         { "38", Element.Life },
//         { "239", Element.Life },
//         { "74", Element.Death },
//         { "78", Element.Dragon },
//         { "260", Element.Fire },
//         { "70", Element.Fire },
//         { "109", Element.Death },
//         { "111", Element.Water },
//         { "112", Element.Earth },
//         { "130", Element.Dragon },
//         { "72", Element.Earth },
//         { "235", Element.Dragon },
//         { "56", Element.Dragon },
//         { "113", Element.Life },
//         { "200", Element.Dragon },
//         { "236", Element.Fire },
//         { "240", Element.Dragon },
//         { "254", Element.Water },
//         { "257", Element.Water },
//         { "258", Element.Death },
//         { "259", Element.Earth },
//         { "261", Element.Life },
//         { "262", Element.Dragon },
//         { "278", Element.Earth },
//         { "73", Element.Life }
//     };